[package]
name = "torus_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
torus_core = { path = "../torus_core" }
bevy = { version = "0.5.0" }
bevy_asset_loader = { git = "https://github.com/NiklasEi/bevy_asset_loader", branch = "main" }
bevy_kira_audio = { version = "0.6.0" }
bevy_networking_turbulence = { version = "0.3.3" }
bevy_advanced_input = { git = "https://github.com/sadpython/bevy_advanced_input.git", branch = "main" }
rand = "0.8.3"
serde = "1.0"
num = "0.4.0"